### ISSUE TITLE
Sucess Test vs Fail Test

### ISSUE THREAD

**Issue by lorranpalmeira** [formulahendry/vscode-dotnet-test-explorer#103]
Sometimes tests passed, but the flag next to test has fail.

![image](https://user-images.githubusercontent.com/18705060/42694681-993194b0-8689-11e8-8da3-a6b1dcec690b.png)

All my tests are sucessful

![image](https://user-images.githubusercontent.com/18705060/42694719-b072469c-8689-11e8-872a-a05ec84c3eae.png)

![image](https://user-images.githubusercontent.com/18705060/42694735-bae12eae-8689-11e8-9bc0-0289a4c89e9c.png)

**Comment by stefanforsberg** [comment]
Hmm, for the test case we have one method but potentially multiple results (for instance, numeroA passes and numeroB fails) so that could cause code lens to display an unexpected icon. But by the looks of the second screenshot all tests are passing...

Can you help with some steps to reproduce the error?

**Comment by lorranpalmeira** [comment]
I tried reproduce this error with xunit and doesnt happen again.
Maybe before my test was with nunit or VsCode had a problem possibily.

Thanks for the feedback.

**Comment by stefanforsberg** [comment]
Ok, closing this issue, feel free to open a new one if you can reproduce the error.
