### ISSUE TITLE
When using MS test and the "DataRow" attribute hides testcases

### ISSUE THREAD

**Issue by Mgenuit** [formulahendry/vscode-dotnet-test-explorer#140]
## Intro
This bug was found to exist on the master branch as part of testing the fix of issue 137.
This behavior might be because of the way MsTest works and really hard(if not impossible) to change.
### Bug present on
* __Branch:__  Master
* __Last Commit__: 084b1baafc7cfb0368ad7df17ca7d7a9264d3b47
### Steps to preproduce
1. Open the MsTest test cases
2. Refresh test explorer so that all testcases are displayed
_Testclass1 should have a testcase ”DataTest” _
3. press the arrow on the right of testcase “Pass”
### Expected result
The test explorer should have shown two testcases “Datatest (First)” and “Datatest (Second)” after refreshing the testcases.
### Experienced result
The test explorer shows one testcase “Datatest. After running that testcase two testcases are added “Datatest (First)” and “Datatest (Second)” and displayed as having passed.

**Comment by stefanforsberg** [comment]
This is because of how vstest reports discovery. When you run all tests the actual test results finds the test cases and adds them to the tree. It can not run a specific test (which I think is that vstest once again doesn't recognize the format).

I'm going to close this since this is not something that we can really fix on our end.
