### ISSUE TITLE
Could not find test (namespace not matching uri)

### ISSUE THREAD

**Issue by fdncred** [formulahendry/vscode-dotnet-test-explorer#163]
All my vstests are found however when I click on them i get the error message, "Could not find test (namespace not matching uri)". It would be helpful to print out the namespace and the non-matching uri in order for me to determine what's messed up in my project. I'm not sure how to further debug this.
`dotnet test -t -v=q` seems to work great and `dotnet vstest "d:\blah\blah\some.test.dll" /ListQualifiedTests /ListTestsTargetPath:"d:\temp\blah"` seems to work as well.

**Comment by stefanforsberg** [comment]
What that error message means is that we could't figure our where that test was located (the default behavior is to open the corresponding test in the editor when clicking it). I guess if you actually try to run the tests (either by right click a test node and selecting run tests, or by running all tests from the menu options at the top of the extension) that will work just fine.

We'll try and rework how this error is reported in the future.

**Comment by fdncred** [comment]
Yes, running them works fine. I just can't navigate to them and I really have no idea what else to change to make them navigable. I assume I need to change my namespace or class name but since I don't know what it's looking for I'm not sure what to change it to.

**Comment by stefanforsberg** [comment]
The current implementation when multiple symbols are matching is somewhat lacking so I wouldn't recommend to change anything on your end to match our requirements for finding a test.

I'll try and see if I can make the experience better in the coming version(s).

**Comment by fdncred** [comment]
ok, thanks. If you want to test on the project I was working on it's [here](https://github.com/Oceania2018/NumSharp).

**Comment by stefanforsberg** [comment]
Thanks! Might as well answer here what the "problem" is.

When we do a symbol search (basically what happens when you press ctrl-t in vscode and search for the symbol yourself) we sometimes have multiple matching symbols. For instance, for your linked repo this might be the case

![image](https://user-images.githubusercontent.com/358570/48021864-eff50d80-e139-11e8-9383-dfb42e0333f9.png)

As is hinted by vscode we don't get any additional information about the symbol apart from the uri pointing to the file containing the symbol. The only case currently where we can map the test is where the test FQN matches the file location.

We do that my replacing the directory separators with dots, so the path test\NumSharp.UnitTest\Operations\NDArray.Addition.Test.cs becomes test.NumSharp.UnitTest.Operations.NDArray.Addition.Test.cs. We then check to see if any of the converted paths contains the full test name (without the test method). 

In your case the test is called NumSharp.UnitTest.NDArrayAdditionTest.ComplexTwo1D and since NumSharp.UnitTest.NDArrayAdditionTest is not contained in the string test.NumSharp.UnitTest.Operations.NDArray.Addition.Test.cs we can't navigate to the symbol.


I don't know if this makes much sense to you, but if you do understand and have some better approach to solve this I'm all ears =)

**Comment by fdncred** [comment]
Name the tests uniquely I guess. If you have no other way of finding out where the tests are I'm not sure what other options we have.

**Comment by fdncred** [comment]
The only other real option would be to "roll your own" and search all the files for "[TestMethod]" methods. Sounds complicated.

**Comment by CPardi** [comment]
Hi, I have a similar issue with my tests. I had a look around and found the document symbol provider described at https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands. 

```typescript
vscode.executeDocumentSymbolProvider
```

I've had a look at what it returns in the debugger for C# code and it gives the document structure from the top level namespace as `DocumentSymbol` instances. The sub-structures are stored within the  `.children` array properties. For F# code it look like the existing `vscode.executeDocumentSymbolProvider` yields the required namespace information anyway.

This looks like it might provide all the information needed to identify the tests.

**Comment by stefanforsberg** [comment]
Hi @CPardi!

Since we don't know what file the symbols are in to start with we execute the executeWorkspaceSymbolProvider. You are correct in suspecting we could then use the executeDocumentSymbolProvider for each of the found symbols (if there are multiple found) and match the symbols from there. However, as I remember it (and this was a while back) the executeDocumentSymbolProvider behaved very unexpectedly when executed multiple times in a row. I can't remember at the top of my head what it was, but maybe it's time to revisit that idea.

**Comment by aalmada** [comment]
I'm running into issue for xUnit theories only. No issues with facts.
It's great that the theories are expanded as different tests but cannot navigate to the test. This may be due to the name generation include the theory parameters.

**Comment by aalmada** [comment]
I'm getting the message **"Could not find test (no symbols found)"** for some of the tests. 
I'm using 0.6.0, with xunit 2.3.1. All tests are on the same netcoreapp2.0 assembly.
I can't find a pattern for the tests that fail. I initially thought it only failed when test name included the theory parameters but it may fail on either cases.

**Comment by stefanforsberg** [comment]
@aalmada @CPardi @fdncred  0.6.4 was just released which should improve the "go to test" functionality. Please give it a try.

**Comment by gerry123** [comment]
I've got "Could not find test (no symbols found)" when the name of the test folder doesn't exactly matches the namespace. E.g.:
Path: .../m5.repository.Tests
Namespace: m5.repository.tests

VSCode: 1.33.1 (Windows 10)
TestExplorer: 0.6.6
