### ISSUE TITLE
Support multiple test projects in a solution/workspace.

### ISSUE THREAD

**Issue by ErikaEllison** [formulahendry/vscode-dotnet-test-explorer#18]
I really appreciate this extension but it would be even more useful if it supported multiple test projects per solution/workspace in settings.json like:
```
{
"dotnet-test-explorer.testProjectPaths": ["path/to/some/test/proj", "path/to/other/test/proj"]
}
```

**Comment by paulinka129** [comment]
It would be great!

**Comment by grankko** [comment]
I came here for this..

**Comment by AlexTeixeira** [comment]
Very good idea. 
Better if the plugin be able to discover project inside a folder

**Comment by krawuzikapuzi** [comment]
I'd love to have this feature too, however since my solution has several test projects, I'm not fond of providing a list of all test projects. Instead, I have a naming convention for all test projects "Some.Thing.Tests". It would be great if it could support a regular expression or similar to show projects matching the expression inside the currently opened folder and allow execution of those tests.

**Comment by christophla** [comment]
Instead of rewriting the test explorer tree, it may be easier to display tests based on the project that is  *focused* (via menu in footer) in OmniSharp.

**Comment by davidparker** [comment]
thumbs up for this one,  I just installed this plugin, and realised it wont actually work as I work with a workspace and have multiple test projects for my dependant projects.   This is not based on solution file, they are individual projects on VSTS that I nuget and then have separate, standalone test projects for.   for now its a deal breaker :(

**Comment by stefanforsberg** [comment]
@christophla That sounds somewhat tempting but do you think it will be good enough? I've moved away from having multiple test projects personally but from what I remember I usually executed more than one at a time which would not be possible with the workspace root solution no?

**Comment by christophla** [comment]
@stefanforsberg When using workspaces, you may, for example, have multiple microservice solutions open, each with its own unit and integration test projects. It's not realistic not combine them into a single test project - especially if they are each coming from different repos.

**Comment by stefanforsberg** [comment]
@christophla I see, that is basically like my current workflow but I've used one vscode window per service. But I can definitely see the merit in running one instance of the editor and adding multiple workspaces. 

But you mention that each solution tend to have a unit and a integration test project, so that would mean that you'd need to two manage at least two test projects in one workspace?

**Comment by christophla** [comment]
@stefanforsberg You are correct. 

It's probably best to approach the multiple test project scenario first and then approach the workspace (multiple project) issue as a separate feature.

**Comment by stefanforsberg** [comment]
Just a small update. I've been working on a bit of restructuring to be able to handle multiple test project per solution / workspace.

Instead of taking a path dotnet-test-explorer.testProjectPath takes a glob that points to the directories that contains tests. So if we were to use our own test directory as example the glob pattern _"+(mstest|nunit|xunittests)"_ will find all those test directories and then will perform the usual test discovery of those directories in parallel. The log looks something like this:

> Starting extension
Finding projects for pattern d:/dev\vscode-dotnet-test-explorer\test/+(mstest|nunit|xunittests)
Found 3 matches for pattern
Adding directory d:/dev/vscode-dotnet-test-explorer/test/mstest
Adding directory d:/dev/vscode-dotnet-test-explorer/test/nunit
Adding directory d:/dev/vscode-dotnet-test-explorer/test/xunittests
Executing dotnet test -t -v=q in d:/dev/vscode-dotnet-test-explorer/test/mstest
Executing dotnet test -t -v=q in d:/dev/vscode-dotnet-test-explorer/test/nunit
Executing dotnet test -t -v=q in d:/dev/vscode-dotnet-test-explorer/test/xunittests

Actual execution of the test are handled in a similar fashion, they are executed in parallel and when they are all finished the tree and code lens and problem views are updated as they are today. The big difference against today is that the test are not executed in the terminal but rather behind the scenes (like test discovery is handled).

Since I'm not actively using any project with multiple test projects I'm keen for someone else to try this version and see if it's something that will be usable at all. Any takers?

**Comment by AlexTeixeira** [comment]
Hi, 

I have multiple project with complex test tree. So in can test a preview version in a macOs system.

And I found a thread about `dotnet test` command that talk about discovering multi project inside a directory : https://github.com/Microsoft/vstest/issues/705

**Comment by stefanforsberg** [comment]
@AlexTeixeira  Cheers!

Unpack the file below and install the .vsix in vscode.

![image](https://user-images.githubusercontent.com/358570/40799876-0a69207c-650f-11e8-950b-6744b27f42cf.png)

[dotnet-test-explorer-0.3.1.zip](https://github.com/formulahendry/vscode-dotnet-test-explorer/files/2059477/dotnet-test-explorer-0.3.1.zip)

**Comment by TimBarley** [comment]
@stefanforsberg Just installed the preview extension and it worked for me without any initial issues.

**Comment by teamdynamiq** [comment]
@TimBarley: Ok great. Out of interest, how many test projects were there in your solution/workspace and about how many tests?

**Comment by qubicaamf** [comment]
@teamdynamiq, in our case we have at least 2 test projects per solution: Unit Tests, IntegrationTests

**Comment by TimBarley** [comment]
>@TimBarley: Ok great. Out of interest, how many test projects were there in your solution/workspace and about how many tests?

@teamdynamiq There are 6 total projects. 2 of them are test projects. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AlexTeixeira** [comment]
Hello,

Sorry for the delay, I have been working only on front-end tasks.

For my side, my architecture seems to be quite more complexe and do not macth any of my tests.

**_This is my project architecture :_** 

<img width="385" alt="capture d ecran 2018-06-11 a 20 44 09" src="https://user-images.githubusercontent.com/6555080/41250791-3b570076-6db8-11e8-9dac-3cd3f3ab6923.png">


All my tests are under the _test folder_.
For this project, I have for class library projects and any one is detected by the plugin.

Should I configure something in my settings ?

**Comment by stefanforsberg** [comment]
@AlexTeixeira You would need to enter a glob that matches the test projects you want added in the testProjectPath setting.

**Comment by AlexTeixeira** [comment]
Back from some test :

I set as project path :     **_"dotnet-test-explorer.testProjectPath": "./test/**/*"_**

But when I reload the tree view I have :

1. Any tests in the tree view
2. CPU go to **100%** for **few seconds to one minutes**, and some dotnet process runs at same time ( for my case **3 at same time**)

**Comment by stefanforsberg** [comment]
@AlexTeixeira 

If you look at the Output/Test Explorer terminal you can see which folders it tries to discover tests in. Currently it tries to do this in parallel so if you've specified an unlucky glob and/or have many test project you're bound to end up with much cpu-usage. Vsocde it's not really built for that kind of processing.

Just out of interest, how many folder can you see it's trying to discover tests in? You should see something like this in the log

> Starting extension
Finding projects for pattern d:/dev\vscode-dotnet-test-explorer\test/+(mstest|nunit|xunittests)
Found 3 matches for pattern

I'm afraid that until MS provides us with multiple test projects supports built in (as a first class citizen, not something that uses undocumented things and requires a serious of burning hoops you'd have to jump through) we're just not getting there. #83 might be such a thing.

**Comment by AlexTeixeira** [comment]
@stefanforsberg .

I found the good glob pattern.
If anyone have something similar to me, this is the pattern that match my tests :

`test/**/*.*[Test]/`

The build and test execution seems to not take to much CPU and time. 
**Few seconds and 44% CPU Usage.**

**Comment by AlexTeixeira** [comment]
Hi,

Just a question. This feature is included into the master branch ? It seems that is not working anymore with the update 4.0 :(

**Comment by stefanforsberg** [comment]
Hey @AlexTeixeira, this feature is not in the master branch.

**Comment by AlexTeixeira** [comment]
Hey @stefanforsberg. Ok, I will back to 0.3.1 with the multi workspace feature :)

**Comment by stefanforsberg** [comment]
@AlexTeixeira Fair enough =)

Just to be clear, that feature is not in the 0.3.1 that was released publically, it's only in the zip file linked above.

**Comment by garfbradaz** [comment]
@stefanforsberg: Any news on when this will be released into master? 

FYI, I love this extension btw.

**Comment by stefanforsberg** [comment]
@garfbradaz I still have not found a way to implement this feature that feels right. Right now I’m on vacation but I will continue to work on a solution later in august. I am well aware that this is a feature many people are waiting for. But right now it’s time for another glass of sangria 💖

**Comment by garfbradaz** [comment]
Fair enough @stefanforsberg enjoy your hols :)

FYI, I tried using your VSIX mentioned above, and I get the following error:

> Starting extension
> Finding projects for pattern c:/code\a2/tests\**\*[test].csproj
> Found 2 matches for pattern
> Evaluating match c:/code/a2/tests/xunit-integration/xunit-integration-tests.csproj
> Adding directory c:/code/a2/tests/xunit-integration/xunit-integration-tests.csproj
> Evaluating match c:/code/a2/tests/XUnit/apitests.csproj
> Adding directory c:/code/a2/tests/XUnit/apitests.csproj
> Executing dotnet test -t -v=q in c:/code/a2/tests/xunit-integration/xunit-integration-tests.csproj
> Executing dotnet test -t -v=q in c:/code/a2/tests/XUnit/apitests.csproj
> [ERROR] Error while executing dotnet test -t -v=q - Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
> 	at exports._errnoException (util.js:1050:11)
> 	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
> 	at onErrorNT (internal/child_process.js:367:16)
> 	at _combinedTickCallback (internal/process/next_tick.js:80:11)
> 	at process._tickCallback (internal/process/next_tick.js:104:9)
> [ERROR] Error while executing dotnet test -t -v=q - Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
> 	at exports._errnoException (util.js:1050:11)
> 	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
> 	at onErrorNT (internal/child_process.js:367:16)
> 	at _combinedTickCallback (internal/process/next_tick.js:80:11)
> 	at process._tickCallback (internal/process/next_tick.js:104:9)
> 

Checked and C:\WINDOWS\system32 is included in my PATH environment variable (WIndows 10 machine).

**Comment by Neutrino-Sunset** [comment]
I've read through this issue and every issue it links to, but I don't understand how to get Test Explorer to discover my test directories. I have a workspace with a project WebServiceTests. If I set `testProjectPath` to `./WebServiceTests` it works. But obviously I have multiple workspaces with tests in different directories and `testProjectPath` is a global user setting which won't work for multiple projects and will not work for anyone else who checks out my project, since they won't have that user setting.

How am I supposed to configure this? There is plenty of talk her, but nothing in the project doumentation page.

**Comment by stefanforsberg** [comment]
@Neutrino-Sunset Currently we do not support multiple workspaces or test projects. We could be clearar on this in the known issues though, thanks for feedback.

**Comment by Neutrino-Sunset** [comment]
Are you saying it is necessary to manually set `testProjectPath` to the name of whichever test project you are currently working on? It doesn't accept wildcards or anything?

**Comment by stefanforsberg** [comment]
It has to point at a specific test project

**Comment by TimBarley** [comment]
I've been using the VSIX, from this thread, for about two months now and I've not had any issues.
My current directory structure is:
Project.One
Project.One.Tests
Project.Two
Project.Two.Tests
...
There are a total of 6 projects with 4 of them having corresponding test projects. Within my workspace settings (I have nothing in user settings), I'm using: `"dotnet-test-explorer.testProjectPath": "./*.Tests"` and it has no problem finding (and running) all of my tests.
The only 'issue' I ran into was when VSCode updated the extension to v4... Took me 30 minutes to realize what happen. :-)

**Comment by stefanforsberg** [comment]
This should be fixed with the v05 update. Please open new issues if something is not working as expected. Thanks for your patience 🌈

**Comment by garfbradaz** [comment]
@stefanforsberg Just back from DIY hols 🛠 

Just seen the update, will have a goosey now and a good test. Top marks for smashing this one out.
