### ISSUE TITLE
Colors don't update for multiple test projects

### ISSUE THREAD

**Issue by andreluizsecco** [formulahendry/vscode-dotnet-test-explorer#181]
If I run all the tests (multiple test projects), the colors are not being updated for all projects, see the image below:

![image](https://user-images.githubusercontent.com/7199850/52431234-f7d49d00-2aee-11e9-9b56-089628657eaa.png)

Any suggestions to solve this?

**Comment by stefanforsberg** [comment]
Hmm, a bit hard to figure out without having more information. Can you reproduce it on something small and share the code?

**Comment by andreluizsecco** [comment]
Yes! See: [https://github.com/andreluizsecco/VSCodeTestExplorer](https://github.com/andreluizsecco/VSCodeTestExplorer)

In this repository, I created 3 test projects with one test method each.
I Added 3 images that illustrate the problem. (Before run, First Run, Refresh Test Explorer)

**Comment by stefanforsberg** [comment]
Ah ok, at the moment you need to configure test explorer with having multiple test projects. The "documentation" for that is [here](https://github.com/formulahendry/vscode-dotnet-test-explorer#configuring-multiple-test-projects), and for your example project a testProjectPath of "**/Test*.csproj" would work.

The reason for this is that when logging the test results only the last test project results are written to the file we view for test results which is why only one project shows up in the tree. Apparently this is perhaps changing in a coming version of the test adapter, I'll keep this issue open and keep this link here to track the issue further.

https://github.com/Microsoft/vstest/pull/1877

**Comment by andreluizsecco** [comment]
It worked for me!
Great, thank you!
