### ISSUE TITLE
Problems with multiple test projects

### ISSUE THREAD

**Issue by keeed** [formulahendry/vscode-dotnet-test-explorer#198]
When there multiple test projects in the application, for example:

A.Tests (2 tests)
B.Test (2 tests)
C.Tests (2 tests)

On initial load of vscode, it will correctly show all the tests and the multiple projects.

However after running the "Play" or "Refresh" method in the UI, the behaviour becomes erratic. Sometimes only B and C are shown. Sometimes A only.

Recently encountered this with the latest release.

**Comment by stefanforsberg** [comment]
Hello. Due to some (coming) changes as how to the test results are reported we were forced to make some adjustments regarding multiple test projects. Apparently I missed the mark here, sorry about that. I'll try and take a look at this asap.

**Comment by stefanforsberg** [comment]
@keeed I'm having a hard time reproducing the errors you're seeing. Are you able to share your project or a simplified version of it?

**Comment by keeed** [comment]
@stefanforsberg  apologies for the late reply.

I've created a sample repository which include the structure that I'm using. The issue is prevalent and can be easily replicated. 😄 

Hope that this helps! If there's anything that you need feel free to message 😄 

Here's the repo: https://github.com/keeed/netcore-test-explorer-sample

**Comment by keeed** [comment]
@stefanforsberg just to add, not sure if this is correlated with this issue but it seems like some tests have already finished but is still showing as being executed.

**Comment by stefanforsberg** [comment]
@keeed Thanks for creating that, now I know what the issue is.

When setting up multiple test directories you need to instruct the extension how to find them (see https://github.com/formulahendry/vscode-dotnet-test-explorer#configuring-multiple-test-projects). Unfortunetly a solution file does not work as of yet due to them overwriting the test results of other projects in the same solution (which is why you're seeing only one project reported in the result). There are changes coming to the test runner that is included in the dotnet sdk v3 but until then you need to configure the extensions as per the link.

Something like this should work for the test repo you linked to
![image](https://user-images.githubusercontent.com/358570/55721100-c733b580-5a02-11e9-8bbd-eda39b88fb9b.png)

**Comment by keeed** [comment]
@stefanforsberg adding the "**/*.Tests.csproj" actually fixed it! Thanks for this one! 

Also, I think that it also fixed the problem where the test is already finished but still shows as executing in the UI. I'll keep checking on this one 😄

**Comment by stefanforsberg** [comment]
Please do and open a new issue of you find anything fishy =)
