### ISSUE TITLE
Feature: Color coded tree view

### ISSUE THREAD

**Issue by dsarfati** [formulahendry/vscode-dotnet-test-explorer#28]
First of all, thanks for creating this extension. Exactly what i was looking for.

It would be great if the tree view icons indicated the test status (pass/fail). Im thinking this could replace the large gray arrow that is next to each test. 

I would be willing to put in some time if you could direct me in the best way of adding this.

**Comment by Micene09** [comment]
Absolutely needed feature in my company.
This is the only reason that brings me to open VS Pro instead of VS Code.

**Comment by stefanforsberg** [comment]
I have a branch of the test explorer that does something like this. After tests are run the explorer looks something like this

![image](https://user-images.githubusercontent.com/358570/35823768-f3366ed6-0ab0-11e8-8285-b6f7f76988c4.png)

At the moment this only works for xunit tests, mostly because that's what I'm using. With some small amount of work I'm sure it would work somewhat ok-ish for nunit also (but the dotnet test -t output for nunit feels a bit lacking at the moment no? This also present problems in the current test explorer when multiple test has the same name) @formulahendry What's your opinion on pull request that are features only for a given test framework?

**Comment by dsarfati** [comment]
This looks awesome. Are you pulling the results the same way that the code lens gets the results?

**Comment by stefanforsberg** [comment]
Yes, it uses the same result file that the code lense is using.

About the status roll up is should be doable, I'll see when I find the time to tinker with it.

**Comment by janaka** [comment]
@dsarfati note PR #32 got rolled into #35. I believe @stefanforsberg had added test result rollup.

**Comment by stefanforsberg** [comment]
@dsarfati 0.2.1 is released now which features the color coded tree for xunit tests.

**Comment by janaka** [comment]
Closing as we have moved forward with this.
