### ISSUE TITLE
Doesn't find NUnit Test project 

### ISSUE THREAD

**Issue by bernardbr** [formulahendry/vscode-dotnet-test-explorer#77]
Hello, in this new version, the TestExplorer doesn't find the NUnit test project.

Please see, the image below:
![image](https://user-images.githubusercontent.com/4705034/40074540-3f51ba5e-5850-11e8-91f0-9a434d723d84.png)

Regards

**Comment by stefanforsberg** [comment]
Hey, was this project working before 0.3? If you go to the output/test explorer terminal what does it say?

![image](https://user-images.githubusercontent.com/358570/40177666-82b7c7e4-59df-11e8-961e-7ceb7287d535.png)

**Comment by bernardbr** [comment]
Ops! I did a Downgrade to 0.23 version and got the same issue.
Are something wrong on my project?

When I use codeLens the test runs fine...

**Comment by bernardbr** [comment]
I reproduced the issue here: https://github.com/bernardbr/vscode-dotnet-test-explorer-issues-77-example

**Comment by stefanforsberg** [comment]
Hey @bernardbr! The code lense integration (if you by that mean the Run test / Debug test above the test method) is actually not from our extension but from the omnisharp one.

I'll take a look at your issues soonish, thanks for the reproduction 🍒

**Comment by stefanforsberg** [comment]
@bernardbr I'm not able to reproduce your error but I have a suspicion that the error stems from the fact that you're running some sort of spanish localisation of the cli. For nunit (and mstest) we have to parsed the actuall dll:s being tested (using the regexp _/^Test run for (.+\.dll)\(.+\)/gm_) which I guess will not handle the spanish output (or any other language for that matter).

Does this sound like a reasonable error cause @jmansar?

**Comment by jmansar** [comment]
Yes that sounds right. The possible solution might be setting ` DOTNET_CLI_UI_LANGUAGE` to `en-US` before running `dotnet test` to override the system language.

**Comment by stefanforsberg** [comment]
DId a quick try of setting the DOTNET_CLI_UI_LANGUAGE to es and that changed the output of dotnet -h to spanish but dotnet build and dotnet test output is still in english.

**Comment by stefanforsberg** [comment]
Upgraded to the latest sdk and now dotnet build is outputed in spanish but dotnet test is still in english.

@bernardbr If you execute dotnet test in your repro-repo, what is the output of that command?

**Comment by bernardbr** [comment]
@stefanforsberg I've tried to run ```set DOTNET_CLI_UI_LANGUAGE=en``` but it didn't work...

**Comment by bernardbr** [comment]
Thank you very much @stefanforsberg and @jmansar 
Using the solution (remove language folder in SDK path): Microsoft/vstest#821
The Test Explorer worked fine!

![image](https://user-images.githubusercontent.com/4705034/40253519-6d9e93ec-5ab6-11e8-9796-9a29eb737999.png)

**Comment by stefanforsberg** [comment]
Glad you found something that works, looks like this is the workaround until we (or rather the cli team) comes up with a better solution then. Thanks @bernardbr.

**Comment by shinfd** [comment]
Hello.

(Adding here since I felt this was the most appropriate place even after being closed...)

Seeing #209 was integrated after 0.7.0, I was hoping this may have been resolved by now, but found the extension still unable to list tests in my Japanese environment, without `removing language folder in SDK path` mentioned in this issue. The DOTNET_CLI_UI_LANGUAGE is for some strange reason not observed just for the DLL line.

Instead of relying on the English string "Test run for ",  how does using the directory path as the key for extracting the DLL sound? I played around editing the extension's js file directly and below modification got refresh to seemingly work properly without hacking SDK.

```
function extractAssemblyPaths(testCommandStdout, testDirectoryPath) {
    var escapedTestDirectoryPath = testDirectoryPath.replace(/[-^$*+?.()|[\]{}]/g, '\\$&').replace(/[\\/]/g, '[\\\\/]');
    const testRunLineRegex = new RegExp(`(${escapedTestDirectoryPath}.+\\.dll)\\(.+\\)`, 'gm');
    ...
```

Note that the caller function (discoverTests) have to be modified accordingly. I have only tested this on Win10 JP and in a small test environment, so there's a chance I have overlooked something. Escape may be overkill.

As an aside, it may help to add --nologo when calling `dotnet test`, slightly shortening the text to be parsed by regex.

Regards.

**Comment by marcanpilami** [comment]
I can confirm that with 0.7.4 I still have the issue on my French machine despite #209. When run on CLI, `dotnet test -t -v=q` with `DOTNET_CLI_UI_LANGUAGE=en` gives an English list of tests as expected.

@stefanforsberg: can this issue be reopened? Available for tests if needed.

**Comment by Henry-Jones** [comment]
This isssue is still present in 0,7.5. It helps to rename the local language folder in the .Net Core SDK but a permanent solution would be better. Maybe this can help: [change language in Powershell](https://social.technet.microsoft.com/Forums/windowsserver/en-US/6ed8f2d9-082a-4c86-8066-e9b2391f5dff/how-to-change-language-in-powershell-to-english)

I also offer help in testing.
