### ISSUE TITLE
BUG: XUnit Tests Do Not Show Passing or Failing Status Test Explorer 

### ISSUE THREAD

**Issue by shahabganji** [formulahendry/vscode-dotnet-test-explorer#85]
As the title says when a test passed or failed the indicator does not get updated for the test which has been run. It displays a loading or in progress indicator next to the test name in Test Explorer.

![test](https://user-images.githubusercontent.com/4405518/40883519-52a625f4-6714-11e8-85d9-cadaadbcf809.jpg)

**Comment by stefanforsberg** [comment]
Hey, how did you execute the test (run all tests, run specific test, the Run test link in code lens etc)?

**Comment by shahabganji** [comment]
@stefanforsberg I used the arrow next to the test name in test explorer, and BTW my OS was Windows 7, it just works fine on my Mac though.

**Comment by shahabganji** [comment]
I faced another problem in My mac environment, no matter which method I choose to run the tests. my test units fail to build but the status is a success 😩 

<img width="917" alt="screen shot 2018-06-04 at 18 23 17" src="https://user-images.githubusercontent.com/4405518/40921410-9fc9fbba-6824-11e8-9e3c-8614bfeddcba.png">


<img width="443" alt="screen shot 2018-06-04 at 18 23 26" src="https://user-images.githubusercontent.com/4405518/40921419-a3cf7b4a-6824-11e8-9d73-73038041083f.png">

**Comment by stefanforsberg** [comment]
@shahabganji:
The first one might be related to not having access rights to the os temp directory (check the first known issue here and see if that helps: https://github.com/formulahendry/vscode-dotnet-test-explorer#known-issues)

The second one is interesting. We keep the state of the test from previous runs so that if you for instance only run the test Can_Generatre_Page_Links it does not change Can_Paginate and Can_Send.. since they were not run. A failed build is thus treated as no new test results so if you were to go from a successful build with all test runs being green they would still be green even after a failed builed caused no tests to run.

**Comment by stefanforsberg** [comment]
If we were able to detect the failed build (which I'm not sure we are outside of parsing the text of the output) what would be the expected state of the tree? All tests being red?

**Comment by shahabganji** [comment]
No, you are right, I had some misunderstandings :see_no_evil: my bad :+1:

**Comment by stefanforsberg** [comment]
Ok, feel free to open another issue if you can come up with a better way of informing the user that the build failed =)

**Comment by shahabganji** [comment]
> The first one might be related to not having access rights to the os temp directory (check the first known issue here and see if that helps: https://github.com/formulahendry/vscode-dotnet-test-explorer#known-issues)

my dot net core version is 2.1.300, and I still have this problem.

**Comment by stefanforsberg** [comment]
I was referring to this: "Try and change the setting dotnet-test-explorer.pathForResultFile to point to a folder you have access right too")
