### ISSUE TITLE
pathForResultsFile creates unpredictable subfolder to store results file.

### ISSUE THREAD

**Issue by colinthompson** [formulahendry/vscode-dotnet-test-explorer#88]
When `dotnet-test-explorer.pathForResultsFile` is set, the extension does not store the results file within that directory; it creates a randomly-named subdirectory and stores the results file in that. This means that it's not practical to update the results file outside of the extension.

I'd like to use `dotnet watch` to automatically run tests whenever the source is modified, but that doesn't update the codelens or the results in the test view panel. If the results file was placed directly in the specified directory, then it'd be an easy matter to tell `dotnet watch` to update the same `Results.trx` file as the extension.

## Current Behaviour
The extension creates a subdirectory such as `test-explorer-jNsG5F` (last six characters are randomly generated by Node.js's `fs.mkdtempSync` function). The test results file is stored within this test-explorer subdirectory.

## Expected Behaviour
When the user specifies a directory within which to store the results file, the extension should store the `Results.trx` file directly within that directory, so long as the directory exists.

I've got this change made at colinthompson/vscode-dotnet-test-explorer@8be5d24; if you agree with my idea, I'm happy to submit a pull request.

**Comment by stefanforsberg** [comment]
Many people have been asking the extension to support multiple test projects per solution / workspace and unfortunately this feature (at least in my head) makes dotnet watch hard(er) to implement. Incoming wall of text ^^

### The test result files
When we run multiple test project we need to make sure the result file is unique so for MyTestProjectOne it would give c:\PathForResultsFile\MyTestProjectOne.trx, for MyTestProjectTwo it would give c:\PathForResultsFile\MyTestProjectTwo.trx etc.

### Event being fired for new tests run
Since we only want to fire ONE event of tests being run we need to move away from the current method of listening to file changes in c:\PathForResultsFile. Instead we run all tests in their respective directory (MyTestProjectOne, MyTestProjectTwo etc) and when they have all finished we read their corresponding trx file and fire the event.

### The problem
When we stop watching files for changes we have no way of knowing that dotnet watch has run tests and thus we don't know that the tree should be updated.

### The solution?
I'm currently at a loss on what a good solution to support these two different feature requests looks like. The concept of detecting whether the current directory just consist of one test directory and then setup a file watch feels wonky at best. Any ideas would be greatly appreciated.

**Comment by colinthompson** [comment]
Oops, I should have realized this would tie in with the multiple test projects effort.

I noticed that - when using dotnet watch - the codelens icons would be updated whenever the trx file was modified. I don't know much (anything, really) about VS Code extension development, but it seems like something's already picking up on the trx file change event and updating codelens. It's just that the UI in the test explorer wasn't updating.

As for reconciling the desire for multiple projects and supporting `dotnet watch`, would it be possible to use the fact that (as I understand it) any test project would reference a test runner of some kind? That would help determine which directories contain tests, and from there maybe have one result file per project?

**Comment by stefanforsberg** [comment]
There is a way of making this work with 0.3 (but it will in all likelihood stop working once the multiple projects release get released).

1. Run all tests in your project.

2. In the terminal it will show you the chosen name of the trx file 
![image](https://user-images.githubusercontent.com/358570/41217811-5b26168a-6d59-11e8-9d11-4a14e90b851d.png)

3. Copy that command and add the watch command ( dotnet watch test --logger "trx;LogFileName=C:\Use...)

4. Now both tree and code lens should be updated when changing files.

![update](https://user-images.githubusercontent.com/358570/41217883-95eafea2-6d59-11e8-96a8-06adaa4683fd.gif)

**Comment by colinthompson** [comment]
Thanks, that's probably what I'll end up doing.

**Comment by stefanforsberg** [comment]
Hey, 0.3.1 was just released which contains a setting called autoWatch. If you set that to true the extension should start watching after test discovery is completed. Give that a spin and please come back with feedback =)

**Comment by colinthompson** [comment]
Looks pretty good overall, thanks for pushing this out.
