### ISSUE TITLE
testDiscovery - extractAssemblyPaths fails in german language

### ISSUE THREAD

**Issue by HrspdFloEngel** [formulahendry/vscode-dotnet-test-explorer#96]
Hi,

When I run the extension on my Win10 EN Laptop test discovery works just fine. On my german Win 10 however it throws this error:

	
	Testlauf f?r "c:\Projects\Project1\src\Project1.Tests\bin\Debug\netcoreapp2.0\Project1.Tests.dll" (.NETCoreApp,Version=v2.0)
	Microsoft (R) Testausf?hrungs-Befehlszeilentool Version 15.7.0
	Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.
	
	at executeDotnetTest.then (C:\Users\engel\.vscode\extensions\formulahendry.dotnet-test-explorer-0.3.1\out\src\testDiscovery.js:17:19)
	at <anonymous>

testDiscovery.js extractAssemblyPaths defines
`const testRunLineRegex = /^Test run for (.+\.dll)\(.+\)/gm; `
which works if dotnet test would return only english. 

One rather ugly solution is to rename/delete the language directory in C:\Program Files\dotnet\sdk\2.1.201. But that's not a really future proof solution.

Is there a way to 
a) Support multiple languages in test discovery?
b) Force dotnet test to output english here?

**Comment by stefanforsberg** [comment]
Hey, last time this was up (#77) we ended up with the rename/delete solution because of how inconsistent the dotnet tool chain was with respecting language preferences.

However, if you do come up with a clever way to work around it we love pull requests =)

(And there is also always the option to run xunit)
